ebot:
  image: "quay.io/galexrt/ebot:latest"
  environment:
    EBOT_IP: "YOUR_EBOT_IP"
    MYSQL_USER: "ebot"
    MYSQL_PASS: "ebot"
    MYSQL_DB: "ebot"
    MYSQL_HOST: "YOUR_MYSQL_HOST"
    MYSQL_PORT: "3306"
  volumes:
    - "/opt/ebot/demos:/ebot/demos"
