database:
  image: "sameersbn/mysql:latest"
  environment:
    DB_NAME: "ebot"
    DB_USER: "ebot"
    DB_PASS: "ebot"
  volumes:
    - "/opt/mysql/data:/var/lib/mysql"
ebot:
  image: "quay.io/galexrt/ebot:latest"
  environment:
    EBOT_IP: "YOUR_EBOT_IP"
    MYSQL_USER: "ebot"
    MYSQL_PASS: "ebot"
    MYSQL_DB: "ebot"
    MYSQL_HOST: "database"
    MYSQL_PORT: "3306"
  volumes:
    - "/opt/ebot/demos:/ebot/demos"
